---

- name: Creating .ssh directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
  when: ssh_keys | list or ssh_config | string

- name: Installing keys
  no_log: yes
  block:
    - name: Installing ssh keys
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.ssh/{{ item }}"
        mode: "0600"
      register: ssh_keys_result
      with_items: "{{ ssh_keys  }}"

    - name: Installing ssh config
      copy:
        src: "{{ ssh_config }}"
        dest: "{{ ansible_env.HOME }}/.ssh/config"
        mode: "0600"
      when: ssh_config | string

- name: Clearing previous keys
  command: ssh-add -D
  when: ssh_keys_result.changed

- name: Adding keys to ssh agent
  command: ssh-add -K "{{ ansible_env.HOME }}/.ssh/{{ item }}"
  when: "ssh_keys_result.changed and 'pub' not in item"
  with_items: "{{ ssh_keys  }}"
